defaults: &defaults
  docker:
    - image: circleci/android:api-27-alpha
  environment:
    _JAVA_OPTIONS: -Xmx1024m -XX:MaxPermSize=256m
    JVM_OPTS: -Xmx1024m -XX:MaxPermSize=256m
    GRADLE_OPTS: -Xmx1024m -Dorg.gradle.jvmargs='-Xmx1024m -XX:MaxPermSize=256m'
version: 2
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - run: chmod +x ./gradlew
      - run: ./gradlew test assemble

workflows:
  version: 2
  build_and_test_plugin:
    jobs:
      - build_and_test
